export default{
    LOGIN:{
        path:'/user/login',
        auth:false
    },
    CREATE_USER:{
        path:'/user/create',
        auth:false
    },
    SEND_MAIL:{
        path:'/email/send',
        auth:true
    },
    GET_ALL_MAIL:{
        path:'/email/inbox',
        auth:true
    },
    GET_SEND_MAIL:{
        path:'/email/getSendMail',
        auth: true
    },
    GET_MAIL_BY_ID:{
        path:'/email/getMailById',
        auth: true
    },
    MOVE_TO_TRASH:{
        path:'email/moveToTrash',
        auth:true
    },
    GET_TRASH_MAILS:{
        path:'email/getTrashMails',
        auth:true
    },
    DELETE_EMAIL:{
        path:'email/emptyTrash',
        auth:true
    },
    GET_DRAFT_MAILS:{
        path:'email/getDraftMails',
        auth:true
    },
    UPDATE_DRAFT:{
        path:'email/updateDraft',
        auth:true
    },
    GET_STARED_MAILS:{
        path:'email/staredMails',
        auth:true
    },
    UPDATE_STARED:{
        path:'email/star',
        auth:true
    },
    SAVE_DRAFT:{
        path:'email/saveDraft'
    }
    
}